/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 aphrodite.gltf --transform 
Files: aphrodite.gltf [66.23MB] > aphrodite-transformed.glb [3.73MB] (94%)
Author: Virtual Museums of Małopolska (https://sketchfab.com/WirtualneMuzeaMalopolski)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/aphrodite-of-milos-a-plaster-cast-db693358e0054ccf917bbe763455cd5e
Title: "Aphrodite of Milos", a plaster cast
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/aphrodite-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rz_123_Afrodyta_z_Melos_119K_0.geometry} material={materials.defaultMat} position={[18.663, 112.118, -37.239]} rotation={[-1.321, -1.152, -1.555]} />
    </group>
  )
}

useGLTF.preload('/aphrodite-transformed.glb')
